name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

env:
  tf_version: 1.5.6
  tg_version: 0.50.2
  working_dir: terraform/live
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  lint-and-security-check:
    name: Run TFLint and TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GPG
        run: |
          echo -n "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Install TFSec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

      - name: Run TFLint
        run: |
          cd terraform/live
          tflint

      - name: Run TFSec
        run: |
          cd terraform/live
          tfsec .
 
  terragrunt-plan:
    runs-on: ubuntu-latest
    needs: [ lint-and-security-check ]
    # Define environment variables for AWS and Terragrunt
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_account_id: ${{ vars.TF_VAR_account_id }}  # Assuming this is a secret

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Create Terraform Plugin Cache Dir
      run: mkdir -p .terraform.d/plugin-cache
      
    - name: Terraform Plugin Cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.6  # Specify your Terraform version
        terraform_wrapper: false

    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.2/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt

    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive --terragrunt-working-dir ${{ env.working_dir }}
