name: Terragrunt Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-security-check:
    name: Run TFLint and TFSec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Install TFSec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec --version

      - name: Run TFLint
        run: |
          cd terraform/live
          tflint

      - name: Run TFSec
        run: |
          cd terraform/live
          tfsec .
 
  terragrunt-plan:
    runs-on: ubuntu-latest

    # Define environment variables for AWS and Terragrunt
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_account_id: ${{ vars.TF_VAR_account_id }}  # Assuming this is a secret
      TERRAGRUNT_DOWNLOAD: /tmp/terragrunt

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH key for access
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 2: Set up Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Specify your Terraform version
    
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Install Terragrunt
    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.2/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt

    # Step 4: Initialize Terragrunt and run plan

    - name: Terragrunt Plan
      run: terragrunt run-all plan --terragrunt-non-interactive --terragrunt-working-dir terraform/live/global/route53/zones

  terragrunt-deploy:
    runs-on: ubuntu-latest
    needs: terragrunt-plan
    # Define environment variables for AWS and Terragrunt
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_account_id: ${{ vars.TF_VAR_account_id }}  # Assuming this is a secret
      TERRAGRUNT_DOWNLOAD: /tmp/terragrunt

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH key for access
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 2: Set up Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Specify your Terraform version
    
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Install Terragrunt
    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.2/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
        chmod +x /usr/local/bin/terragrunt

    # Step 4: Initialize Terragrunt and run plan
    - name: Terragrunt apply
      run: terragrunt run-all apply --terragrunt-non-interactive --terragrunt-working-dir terraform/live/global/route53/zones
